### ISSUE TITLE
Nothing to compare

### ISSUE THREAD

**Issue by christoga** [id-python/direktori#40]
Halo! Saya Andre Christoga, ini github saya yg baru karena github yg kemaren di ban :joy: 

Kali ini saya sudah melakukan semua yg disuruh [ikut.md](https://github.com/id-python/direktori/blob/master/ikut.md)

Ketika saya melakukan compare.. :  

```
There isn’t anything to compare.

id-python:master and christoga:master are identical.
```

Tolong dibantu ya thx.

All the best,
Andre Christoga
Young Developer
andre.christoga@gmail.com

**Comment by edwinlunando** [comment]
Saya lihat https://github.com/christoga/direktori/commits/master

Kamu belum push apa-apa ke repo kamu.

**Comment by christoga** [comment]
oh iya lupa :joy:  hehe

**Comment by gchandrasa** [comment]
kalo boleh tahu, kena ban gara2 apa ya?

**Comment by christoga** [comment]
Kemudaan :joy: 
Saya masih umur 11 tahun :smile: 

Tapi udah bisa ngoding sih :sunglasses:

**Comment by christoga** [comment]
Saya sudah ajukan pull request ya! :smile:

**Comment by iromli** [comment]
@christoga PR sudah di-_merge_ ke `master` branch; closing ...

**Comment by christoga** [comment]
Ok om! kalau mau belajar python dimana ya?
Sekalian kalau mau dicompile javanya bagaimana? 
Thx! :smile:
